---
- name: YA LUBLU VSEH
  yum:
    name: epel-release
    state: present
- name: YA LUBLU VSEH
  yum:
    name: nginx
    state: latest
  tags:
      nginx-package
      packeges
- name: YA LUBLU VSEH
  template:
    src: nginxweb1.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
  tags:
    - nginx-configuration
- name: YA LUBLU VSEH
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
  notify:
    - restart nginx
  tags:
    - nginx-configuration
- name: YA LUBLU VSEH
  systemd:
    name: firewalld
    state: stopped
    enabled: no

